const symptoms = [
     { "symptom": "Fever" },
     { "symptom": "Headache" },
     { "symptom": "Fatigue" },
     { "symptom": "Nausea" },
     { "symptom": "Vomiting" },
     { "symptom": "Diarrhea" },
     { "symptom": "Cough" },
     { "symptom": "Shortness of breath" },
     { "symptom": "Chest pain" },
     { "symptom": "Sore throat" },
     { "symptom": "Runny nose" },
     { "symptom": "Congestion" },
     { "symptom": "Sneezing" },
     { "symptom": "Body aches" },
     { "symptom": "Joint pain" },
     { "symptom": "Muscle weakness" },
     { "symptom": "Dizziness" },
     { "symptom": "Fainting" },
     { "symptom": "Rapid heartbeat" },
     { "symptom": "Palpitations" },
     { "symptom": "High blood pressure" },
     { "symptom": "Low blood pressure" },
     { "symptom": "Chills" },
     { "symptom": "Sweating" },
     { "symptom": "Weight loss" },
     { "symptom": "Weight gain" },
     { "symptom": "Loss of appetite" },
     { "symptom": "Increased appetite" },
     { "symptom": "Difficulty swallowing" },
     { "symptom": "Heartburn" },
     { "symptom": "Indigestion" },
     { "symptom": "Abdominal pain" },
     { "symptom": "Bloating" },
     { "symptom": "Constipation" },
     { "symptom": "Excessive gas" },
     { "symptom": "Bloody stool" },
     { "symptom": "Urinary frequency" },
     { "symptom": "Urinary urgency" },
     { "symptom": "Painful urination" },
     { "symptom": "Blood in urine" },
     { "symptom": "Decreased urine output" },
     { "symptom": "Frequent thirst" },
     { "symptom": "Dry mouth" },
     { "symptom": "Excessive salivation" },
     { "symptom": "Difficulty sleeping" },
     { "symptom": "Insomnia" },
     { "symptom": "Excessive sleepiness" },
     { "symptom": "Restlessness" },
     { "symptom": "Nightmares" },
     { "symptom": "Difficulty concentrating" },
     { "symptom": "Memory problems" },
     { "symptom": "Confusion" },
     { "symptom": "Mood swings" },
     { "symptom": "Irritability" },
     { "symptom": "Anxiety" },
     { "symptom": "Depression" },
     { "symptom": "Panic attacks" },
     { "symptom": "Hallucinations" },
     { "symptom": "Delusions" },
     { "symptom": "Paranoia" },
     { "symptom": "Tremors" },
     { "symptom": "Muscle twitching" },
     { "symptom": "Seizures" },
     { "symptom": "Loss of coordination" },
     { "symptom": "Numbness or tingling" },
     { "symptom": "Sensitivity to touch" },
     { "symptom": "Vision changes" },
     { "symptom": "Double vision" },
     { "symptom": "Blurred vision" },
     { "symptom": "Eye pain" },
     { "symptom": "Ringing in the ears (tinnitus)" },
     { "symptom": "Hearing loss" },
     { "symptom": "Vertigo" },
     { "symptom": "Skin rash" },
     { "symptom": "Itching" },
     { "symptom": "Redness or swelling" },
     { "symptom": "Bruising" },
     { "symptom": "Bleeding gums" },
     { "symptom": "Easy bruising" },
     { "symptom": "Hair loss" },
     { "symptom": "Nail changes" },
     { "symptom": "Joint swelling" },
     { "symptom": "Warmth or redness over a joint" },
     { "symptom": "Limited range of motion" },
     { "symptom": "Stiffness" },
     { "symptom": "Bone pain" },
     { "symptom": "Easy fractures" },
     { "symptom": "Weakness in limbs" },
     { "symptom": "Difficulty walking" },
     { "symptom": "Falls" },
     { "symptom": "Loss of balance" },
     { "symptom": "Nausea with movement (motion sickness)" },
     { "symptom": "Difficulty breathing while lying down (orthopnea)" },
     { "symptom": "Chest tightness" },
     { "symptom": "Wheezing" },
     { "symptom": "Cyanosis (bluish discoloration of lips or skin)" },
     { "symptom": "Swollen lymph nodes" },
     { "symptom": "Night sweats" },
     { "symptom": "Excessive thirst" },
     { "symptom": "Excessive hunger" }
]

export default symptoms;